variables:
  GO_VERSION: 1.21.12

  # Docker
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: "1"
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "/certs/client"

  # Build
  BUILDER_VERSION: "1.0.0"

stages:
  - test
  - prepare
  - build_image
  - build_bundle

.rules-template:
  rules:
    - if: $CI_COMMIT_TAG

# Ugly workaround to get docker:dind working
services:
  - name: docker:dind
    alias: docker
    command:
      - /bin/sh
      - -c
      - "update-ca-certificates && dockerd-entrypoint.sh || exit"


test:
  extends: .rules-template
  stage: test
  image: golang:${GO_VERSION}
  script:
    - cd operator
    - make test
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG
      when: never

# Build the builder image
build_bundle_builder:
  extends: .rules-template
  stage: prepare
  image: docker:cli
  before_script:
    - update-ca-certificates
    # Docker login
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
      if ! docker pull $CI_REGISTRY_IMAGE/builder:$BUILDER_VERSION; then
        # Build and push the builder image
        docker build --build-arg GOLANG_VERSION=$GO_VERSION -f builder.Dockerfile -t $CI_REGISTRY_IMAGE/builder:$BUILDER_VERSION .
        docker push $CI_REGISTRY_IMAGE/builder:$BUILDER_VERSION
      else
        echo "Builder image already exists. Skipping build."
      fi

build_image:
  extends: .rules-template
  stage: build_image
  image: docker:cli
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd operator
    - docker build -t $CI_REGISTRY_IMAGE/operator:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE/operator:$CI_COMMIT_TAG


build_bundle:
  extends: .rules-template
  stage: build_bundle
  image: $CI_REGISTRY_IMAGE/builder:$BUILDER_VERSION
  before_script:
    - update-ca-certificates
  script:
    - cd rq-operator
    - make bundle-build bundle-push BUNDLE_IMG=$CI_REGISTRY_IMAGE/rq-operator-bundle:$CI_COMMIT_TAG
