# permissions for end users to edit resourcequotaconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: resourcequotaconfig-editor-role
rules:
- apiGroups:
  - homelab.server.home
  resources:
  - resourcequotaconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - homelab.server.home
  resources:
  - resourcequotaconfigs/status
  verbs:
  - get
